name: CI

env:
  ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
  ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
  KINDLEGEN: /home/runner/bin/kindlegen/kindlegen
  GIT_PASSWORD:  ${{ secrets.GIT_PASSWORD }}
  GIT_USERNAME:  ${{ secrets.GIT_USERNAME }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: configure Kindlegen directory
        run: mkdir -p $(dirname $KINDLEGEN ) && ls -la $(dirname $KINDLEGEN)

      - uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2
          restore-keys: ${{ runner.os }}-m2

      - name: build and run
        run:  mvn -DskipTests=true -f pom.xml clean package  && java -jar target/*jar
